DROP TABLE IF EXISTS sms CASCADE;
CREATE TABLE sms (
  CODE INT(11) NOT NULL AUTO_INCREMENT,
  MESSAGEID VARCHAR(255) NOT NULL,
  MOBILEORIGINATE VARCHAR(255) NOT NULL,
  MOBILETERMINATE VARCHAR(255) NOT NULL,
  RECEIVETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  TEXT VARCHAR(255) NOT NULL,
  PRIMARY KEY (CODE),
  UNIQUE KEY (MESSAGEID)
) ENGINE='InnoDB' DEFAULT CHARSET='utf8'